### ISSUE TITLE
Should the [wvln] in this formula be in [mm]: "ps > wvln * np.abs(z) / (Wimg * ps)"

### ISSUE THREAD

**Issue by LinYark** [singer-yang/DeepLens#10]
**Position**
This formula "ps > wvln * np.abs(z) / (Wimg * ps)" appears in "Diffraction functions" of /deeplens/optics/wave.py.

**Question**
Should the [wvln] in this formula be in [mm], as follow:
ps > wvln* 1e-3 * np.abs(z) / (Wimg * ps)

**Comment by singer-yang** [comment]
Thank you for your comment! I have corrected this place and will update the code in the next release.
