### ISSUE TITLE
How to get the lenses.json?

### ISSUE THREAD

**Issue by Wu-ssssss** [singer-yang/DeepLens#4]
Dear author, I would like to try other lenses tha are not included in /lenses/camera/xx.json. What should I do to get xx.json?

**Comment by singer-yang** [comment]
Hello,

Thanks a lot for your interest! I would recommend to:
1. read the lens data from a .zmx file, please check geolens.read_lens_zmx() function,
2. or create a template .json file and put the lens data to corresponding positions.

Please feel free to reach out if you are still unclear.

Best,
singer-yang

**Comment by Wu-ssssss** [comment]
> * read the lens data from a .zmx file, please check geolens.read_lens_zmx() function,
> * or create a template .json file and put the lens data to corresponding positions.

Thanks for your reply! I will give it a shot. :muscle:

**Comment by singer-yang** [comment]
Great! Feel free to contact me if you have further questions!
